wip: begin new

diff --git a/irods/library/irods_clerver_auth b/irods/library/irods_clerver_auth
--- a/irods/library/irods_clerver_auth
+++ b/irods/library/irods_clerver_auth
@@ -1,48 +1,51 @@
 #!/bin/bash
 #
 # An ansible module for initializing the clerver connection to the catalog 
-# service providers.
+# service PROVIDERs.
 #
 # Module Name:
 #  irods_clerver_auth
 #
 # Required Variables:
-#  password  the password used by the clerver to connect
+#  PASSWORD  the PASSWORD used by the clerver to connect
 #
 # Optional Variables:
-#  provider  The FQDN of the iRODS server. If this isn't provided, it assumes 
+#  PROVIDER  The FQDN of the iRODS server. If this isn't provided, it assumes 
 #            the local host is the server.
 
 main()
 {
-  local varFile="$1"
+  set -x
+  local VARFILE="$1"
 
-  local provider
-  local password
-  . "$varFile"
+  local PASSWORD
+  local IRODS_HOST
+  local IRODS_PORT
+  local IRODS_USER_NAME
+  local IRODS_ZONE_NAME
+  . "${VARFILE}"
+  local TIME_OUT=20
 
-  require password
+  require PASSWORD IRODS_HOST IRODS_PORT IRODS_USER_NAME IRODS_ZONE_NAME
+  export PASSWORD IRODS_HOST IRODS_PORT IRODS_USER_NAME IRODS_ZONE_NAME
 
-  local authFile
-  authFile=$(iinit -l | sed --quiet 's/^NOTICE: irods_authentication_file - //p')
+  local AUTHFILE
+  AUTHFILE=$(timeout ${TIME_OUT} iinit -l | sed --quiet 's/irods_authentication_file - //p')
+  # AUTHFILE=$(timeout ${TIME_OUT} iinit -l | sed --quiet 's/^NOTICE: irods_authentication_file - //p')
 
-  if [ -z "$authFile" ]
+  if [ -z "${AUTHFILE}" ]
   then
-    authFile="$HOME"/.irods/.irodsA
+    AUTHFILE="${HOME}"/.irods/.irodsA
   fi
 
-  if [ -e "$authFile" ]
+  if [ -e "${AUTHFILE}" ]
   then
     succeed false
   fi
 
-  if [ -n "$provider" ]
-  then
-    export IRODS_HOST="$provider"
-  fi
-
   local errMsg
-  if ! errMsg=$(iinit "$password" 2>&1)
+  # if ! errMsg=$(echo ${PASSWORD} | timeout ${TIME_OUT} iinit "$PASSWORD" 2>&1)
+  if ! errMsg=$(echo ${PASSWORD} | timeout ${TIME_OUT} iinit)
   then
     fail "$errMsg"
   fi
@@ -50,27 +53,33 @@ main()
   succeed true
 }
 
-
 require()
 {
-  local var="$1"
-
-  if [ -z "${!var}" ]
-  then
-    fail "variable '$var' must be defined"
-  fi
+  local VARS="${@}"
+  for VAR in ${VARS}; do
+    if [ -z "${!VAR}" ]
+    then
+      fail "variable '${VAR}' must be defined"
+    fi
+  done
 }
-
 
 fail()
 {
   local msg="$*"
 
   # shellcheck disable=SC2016
+  stderr="$(cat ${stderrfile})"
+  stdout="$(cat ${stdoutfile})"
+  exec 1>&3
   jq --compact-output --monochrome-output --null-input --arg msg "$msg" \
-     '{failed: true, msg: $msg}' \
-    >&2
+    --arg stderr "${stderr}" \
+    --arg stdout "${stdout}" \
+    '$ARGS.named'
+    # >&2
+     # '{failed: true, msg: $msg}' \
 
+  exec 2>&4
   exit 1
 }
 
@@ -79,14 +88,34 @@ succeed()
 {
   local changed="$1"
 
+  stderr="$(cat ${stderrfile})"
+  stdout="$(cat ${stdoutfile})"
   # shellcheck disable=SC2016
+  exec 1>&3
   jq --compact-output --monochrome-output --null-input --arg changed "$changed" \
-     '{changed: ($changed == "true")}' \
-    >&2
+    --arg stderr "${stderr}" \
+    --arg stdout "${stdout}" \
+    '$ARGS.named'
+    # >&2
+     # '{changed: ($changed == "true")}' \
 
+  exec 2>&4
   exit 0
 }
 
 
 set -e
-main "$@" 2>&1
+changed="false"
+rc=0
+stdout=""
+stderr=""
+msg=""
+stderrfile="/tmp/stderr"
+stdoutfile="/tmp/stdout"
+trap 'exec 1>&3 2>&4' 0 1 2 3
+exec 3>&1 4>&2
+exec 1>${stdoutfile}
+exec 2>${stderrfile}
+# trap 'rm -f ${tmpfstderr}' 0 1 2 3
+# main "$@" 2>&1
+main "$@"
